#-------------------------------------------------
#
# Project created by QtCreator 2014-10-18T19:09:45
#
#-------------------------------------------------

QT       += core gui\
            testlib

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = projet_synthese_client
TEMPLATE = app

QMAKE_CXXFLAGS += -std=c++11

SOURCES += src/formegeom.cpp \
    src/main.cpp \
    src/mainwindow.cpp \
    src/point.cpp \
    src/vecteur.cpp \
    src/Couleur.cpp \
    src/groupe.cpp \
    src/segment.cpp \
    src/cercle.cpp \
    src/triangle.cpp \
    src/polygone.cpp \
    src/dessinManager.cpp \
    src/erreur.cpp \
    src/connexion.cpp \
    src/matricecarree2.cpp \
    src/chargementCOR/chargementgroupe.cpp \
    src/tools.cpp

HEADERS  += src/Couleur.h \
    src/formegeom.h \
    src/mainwindow.h \
    tests/testcouleurs.h \
    src/angle.h \
    src/point.h \
    src/vecteur.h \
    src/groupe.h \
    tests/testgroupe.h \
    src/segment.h \
    tests/testsegment.h \
    src/cercle.h \
    src/triangle.h \
    tests/testtriangle.h \
    src/polygone.h \
    src/dessinManager.h \
    src/erreur.h \
    src/dessinable.h \
    src/connexion.h \
    tests/ testpoint.h \
    tests/testpoint.h \
    tests/cunittools.h \
    tests/testlauncher.h \
    tests/cunit.h \
    tests/cunitfacade.h \
    tests/cpptest.h \
    tests/cpptestfacade.h \
    tests/cpptesttools.h \
    tests/testvecteur.h \
    tests/testcercle.h \
    tests/testpolygone.h \
    tests/testangle.h \
    src/matricecarree2.h \
    src/chargementCOR/expert.h \
    src/chargementCOR/chargementfacade.h \
    src/chargementCOR/expertcor.h \
    src/chargementCOR/expertchargement.h \
    src/chargementCOR/chargementsegment.h \
    src/chargementCOR/facade.h \
    src/chargementCOR/chargementtriangle.h \
    src/chargementCOR/chargementcercle.h \
    src/chargementCOR/chargementpolygone.h \
    src/chargementCOR/chargementgroupe.h \
    src/tools.h \
    src/objetgeom.h \
    src/formecomposee.h \
    tests/testforme.h \
    tests/ testpoint.h \
    documentation/latex/class_angle.tex \
    documentation/latex/class_cercle.tex \
    documentation/latex/class_connexion.tex \
    documentation/latex/class_couleurs.tex \
    documentation/latex/class_dessinable.tex \
    documentation/latex/class_dessin_manager.tex \
    documentation/latex/class_groupe.tex \
    documentation/latex/class_polygone.tex

FORMS    += src/mainwindow.ui

OTHER_FILES += \
    contraintes.ods \
    technos.txt \
    DiagrammeDeClasses.dia \
    DiagrammeDeClasses.png \
    rapport/contraintes.ods \
    rapport/DiagrammeDeClasses.dia \
    rapport/DiagrammeDeClassesTemporaire.dia \
    rapport/fonctionnement_chargement.dia \
    rapport/fonctionnement_client_serveur.dia \
    rapport/tests_unitaires.dia \
    rapport/DiagrammeDeClasses.png \
    rapport/rapport.tex \
    rapport/technos.txt \
    documentation/html/dynsections.js \
    documentation/html/jquery.js \
    documentation/html/bc_s.png \
    documentation/html/bdwn.png \
    documentation/html/class_cercle.png \
    documentation/html/class_chargement_cercle.png \
    documentation/html/class_chargement_facade.png \
    documentation/html/class_chargement_groupe.png \
    documentation/html/class_chargement_polygone.png \
    documentation/html/class_chargement_segment.png \
    documentation/html/class_chargement_triangle.png \
    documentation/html/class_dessinable.png \
    documentation/html/class_dessin_manager.png \
    documentation/html/class_exception_couleur_inexistante.png \
    documentation/html/class_exception_traitement_impossible.png \
    documentation/html/class_expert.png \
    documentation/html/class_expert_chargement.png \
    documentation/html/class_expert_c_o_r.png \
    documentation/html/class_forme_composee.png \
    documentation/html/class_forme_geom.png \
    documentation/html/class_groupe.png \
    documentation/html/class_main_window.png \
    documentation/html/class_objet_geom.png \
    documentation/html/class_point.png \
    documentation/html/class_polygone.png \
    documentation/html/class_segment.png \
    documentation/html/class_triangle.png \
    documentation/html/closed.png \
    documentation/html/doxygen.png \
    documentation/html/ftv2blank.png \
    documentation/html/ftv2doc.png \
    documentation/html/ftv2folderclosed.png \
    documentation/html/ftv2folderopen.png \
    documentation/html/ftv2lastnode.png \
    documentation/html/ftv2link.png \
    documentation/html/ftv2mlastnode.png \
    documentation/html/ftv2mnode.png \
    documentation/html/ftv2node.png \
    documentation/html/ftv2plastnode.png \
    documentation/html/ftv2pnode.png \
    documentation/html/ftv2splitbar.png \
    documentation/html/ftv2vertline.png \
    documentation/html/nav_f.png \
    documentation/html/nav_g.png \
    documentation/html/nav_h.png \
    documentation/html/open.png \
    documentation/html/sync_off.png \
    documentation/html/sync_on.png \
    documentation/html/tab_a.png \
    documentation/html/tab_b.png \
    documentation/html/tab_h.png \
    documentation/html/tab_s.png \
    documentation/html/_01testpoint_8h_source.html \
    documentation/html/angle_8h_source.html \
    documentation/html/annotated.html \
    documentation/html/cercle_8h_source.html \
    documentation/html/chargementcercle_8h_source.html \
    documentation/html/chargementfacade_8h_source.html \
    documentation/html/chargementgroupe_8h_source.html \
    documentation/html/chargementpolygone_8h_source.html \
    documentation/html/chargementsegment_8h_source.html \
    documentation/html/chargementtriangle_8h_source.html \
    documentation/html/class_angle.html \
    documentation/html/class_angle-members.html \
    documentation/html/class_cercle.html \
    documentation/html/class_cercle-members.html \
    documentation/html/class_chargement_cercle.html \
    documentation/html/class_chargement_cercle-members.html \
    documentation/html/class_chargement_facade.html \
    documentation/html/class_chargement_facade-members.html \
    documentation/html/class_chargement_groupe.html \
    documentation/html/class_chargement_groupe-members.html \
    documentation/html/class_chargement_polygone.html \
    documentation/html/class_chargement_polygone-members.html \
    documentation/html/class_chargement_segment.html \
    documentation/html/class_chargement_segment-members.html \
    documentation/html/class_chargement_triangle.html \
    documentation/html/class_chargement_triangle-members.html \
    documentation/html/class_connexion.html \
    documentation/html/class_connexion-members.html \
    documentation/html/class_couleurs.html \
    documentation/html/class_couleurs-members.html \
    documentation/html/class_cpp_test.html \
    documentation/html/class_cpp_test_facade.html \
    documentation/html/class_cpp_test_facade-members.html \
    documentation/html/class_cpp_test-members.html \
    documentation/html/class_dessinable.html \
    documentation/html/class_dessinable-members.html \
    documentation/html/class_dessin_manager.html \
    documentation/html/class_dessin_manager-members.html \
    documentation/html/class_erreur.html \
    documentation/html/class_erreur-members.html \
    documentation/html/classes.html \
    documentation/html/class_exception_couleur_inexistante.html \
    documentation/html/class_exception_couleur_inexistante-members.html \
    documentation/html/class_exception_traitement_impossible.html \
    documentation/html/class_exception_traitement_impossible-members.html \
    documentation/html/class_expert.html \
    documentation/html/class_expert_chargement.html \
    documentation/html/class_expert_chargement-members.html \
    documentation/html/class_expert_c_o_r.html \
    documentation/html/class_expert_c_o_r-members.html \
    documentation/html/class_expert-members.html \
    documentation/html/class_facade.html \
    documentation/html/class_facade-members.html \
    documentation/html/class_forme_composee.html \
    documentation/html/class_forme_composee-members.html \
    documentation/html/class_forme_geom.html \
    documentation/html/class_forme_geom-members.html \
    documentation/html/class_groupe.html \
    documentation/html/class_groupe-members.html \
    documentation/html/class_main_window.html \
    documentation/html/class_main_window-members.html \
    documentation/html/class_matrice_carree2.html \
    documentation/html/class_matrice_carree2-members.html \
    documentation/html/class_objet_geom.html \
    documentation/html/class_objet_geom-members.html \
    documentation/html/class_point.html \
    documentation/html/class_point-members.html \
    documentation/html/class_polygone.html \
    documentation/html/class_polygone-members.html \
    documentation/html/class_segment.html \
    documentation/html/class_segment-members.html \
    documentation/html/class_triangle.html \
    documentation/html/class_triangle-members.html \
    documentation/html/class_vecteur.html \
    documentation/html/class_vecteur-members.html \
    documentation/html/connexion_8h_source.html \
    documentation/html/_couleur_8h_source.html \
    documentation/html/cpptest_8h_source.html \
    documentation/html/cpptestfacade_8h_source.html \
    documentation/html/cpptesttools_8h_source.html \
    documentation/html/dessinable_8h_source.html \
    documentation/html/dessin_manager_8h_source.html \
    documentation/html/dir_3fe1b540d32f99d66521f4d105e848f4.html \
    documentation/html/dir_6e88fadedb5d110c56555910975b1e36.html \
    documentation/html/dir_59425e443f801f1f2fd8bbe4959a3ccf.html \
    documentation/html/dir_68267d1309a1af8e8297ef4c3efbcdba.html \
    documentation/html/dir_fceced95d8215eeebebd9df6aa39e1a5.html \
    documentation/html/doxygen.css \
    documentation/html/erreur_8h_source.html \
    documentation/html/exceptioncouleurinexistante_8h_source.html \
    documentation/html/exceptiontraitementimpossible_8h_source.html \
    documentation/html/expert_8h_source.html \
    documentation/html/expertchargement_8h_source.html \
    documentation/html/expertcor_8h_source.html \
    documentation/html/facade_8h_source.html \
    documentation/html/files.html \
    documentation/html/formecomposee_8h_source.html \
    documentation/html/formegeom_8h_source.html \
    documentation/html/functions.html \
    documentation/html/functions_func.html \
    documentation/html/groupe_8h_source.html \
    documentation/html/hierarchy.html \
    documentation/html/index.html \
    documentation/html/mainwindow_8h_source.html \
    documentation/html/matricecarree2_8h_source.html \
    documentation/html/objetgeom_8h_source.html \
    documentation/html/point_8h_source.html \
    documentation/html/polygone_8h_source.html \
    documentation/html/segment_8h_source.html \
    documentation/html/tabs.css \
    documentation/html/testangle_8h_source.html \
    documentation/html/testcercle_8h_source.html \
    documentation/html/testcouleurs_8h_source.html \
    documentation/html/testforme_8h_source.html \
    documentation/html/testgroupe_8h_source.html \
    documentation/html/testlauncher_8h_source.html \
    documentation/html/testpoint_8h_source.html \
    documentation/html/testpolygone_8h_source.html \
    documentation/html/testsegment_8h_source.html \
    documentation/html/testtriangle_8h_source.html \
    documentation/html/testvecteur_8h_source.html \
    documentation/html/tools_8h_source.html \
    documentation/html/triangle_8h_source.html \
    documentation/html/vecteur_8h_source.html \
    documentation/html/search/all_0.js \
    documentation/html/search/all_1.js \
    documentation/html/search/all_2.js \
    documentation/html/search/all_3.js \
    documentation/html/search/all_4.js \
    documentation/html/search/all_5.js \
    documentation/html/search/all_6.js \
    documentation/html/search/all_7.js \
    documentation/html/search/all_8.js \
    documentation/html/search/all_9.js \
    documentation/html/search/all_a.js \
    documentation/html/search/all_b.js \
    documentation/html/search/all_c.js \
    documentation/html/search/all_d.js \
    documentation/html/search/all_e.js \
    documentation/html/search/all_f.js \
    documentation/html/search/classes_0.js \
    documentation/html/search/classes_1.js \
    documentation/html/search/classes_2.js \
    documentation/html/search/classes_3.js \
    documentation/html/search/classes_4.js \
    documentation/html/search/classes_5.js \
    documentation/html/search/classes_6.js \
    documentation/html/search/classes_7.js \
    documentation/html/search/classes_8.js \
    documentation/html/search/classes_9.js \
    documentation/html/search/classes_a.js \
    documentation/html/search/classes_b.js \
    documentation/html/search/functions_0.js \
    documentation/html/search/functions_1.js \
    documentation/html/search/functions_2.js \
    documentation/html/search/functions_3.js \
    documentation/html/search/functions_4.js \
    documentation/html/search/functions_5.js \
    documentation/html/search/functions_6.js \
    documentation/html/search/functions_7.js \
    documentation/html/search/functions_8.js \
    documentation/html/search/functions_9.js \
    documentation/html/search/search.js \
    documentation/html/search/close.png \
    documentation/html/search/mag_sel.png \
    documentation/html/search/search_l.png \
    documentation/html/search/search_m.png \
    documentation/html/search/search_r.png \
    documentation/html/search/all_0.html \
    documentation/html/search/all_1.html \
    documentation/html/search/all_2.html \
    documentation/html/search/all_3.html \
    documentation/html/search/all_4.html \
    documentation/html/search/all_5.html \
    documentation/html/search/all_6.html \
    documentation/html/search/all_7.html \
    documentation/html/search/all_8.html \
    documentation/html/search/all_9.html \
    documentation/html/search/all_a.html \
    documentation/html/search/all_b.html \
    documentation/html/search/all_c.html \
    documentation/html/search/all_d.html \
    documentation/html/search/all_e.html \
    documentation/html/search/all_f.html \
    documentation/html/search/classes_0.html \
    documentation/html/search/classes_1.html \
    documentation/html/search/classes_2.html \
    documentation/html/search/classes_3.html \
    documentation/html/search/classes_4.html \
    documentation/html/search/classes_5.html \
    documentation/html/search/classes_6.html \
    documentation/html/search/classes_7.html \
    documentation/html/search/classes_8.html \
    documentation/html/search/classes_9.html \
    documentation/html/search/classes_a.html \
    documentation/html/search/classes_b.html \
    documentation/html/search/functions_0.html \
    documentation/html/search/functions_1.html \
    documentation/html/search/functions_2.html \
    documentation/html/search/functions_3.html \
    documentation/html/search/functions_4.html \
    documentation/html/search/functions_5.html \
    documentation/html/search/functions_6.html \
    documentation/html/search/functions_7.html \
    documentation/html/search/functions_8.html \
    documentation/html/search/functions_9.html \
    documentation/html/search/nomatches.html \
    documentation/html/search/search.css \
    documentation/latex/class_cercle.pdf \
    documentation/latex/class_chargement_cercle.pdf \
    documentation/latex/class_chargement_facade.pdf \
    documentation/latex/class_chargement_groupe.pdf \
    documentation/latex/class_chargement_polygone.pdf \
    documentation/latex/class_chargement_segment.pdf \
    documentation/latex/class_chargement_triangle.pdf \
    documentation/latex/class_dessinable.pdf \
    documentation/latex/class_dessin_manager.pdf \
    documentation/latex/class_exception_couleur_inexistante.pdf \
    documentation/latex/class_exception_traitement_impossible.pdf \
    documentation/latex/class_expert.pdf \
    documentation/latex/class_expert_chargement.pdf \
    documentation/latex/class_expert_c_o_r.pdf \
    documentation/latex/class_forme_composee.pdf \
    documentation/latex/class_forme_geom.pdf \
    documentation/latex/class_groupe.pdf \
    documentation/latex/class_main_window.pdf \
    documentation/latex/class_objet_geom.pdf \
    documentation/latex/class_point.pdf \
    documentation/latex/class_polygone.pdf \
    documentation/latex/class_segment.pdf \
    documentation/latex/class_triangle.pdf \
    documentation/latex/annotated.tex \
    documentation/latex/class_cercle.eps \
    documentation/latex/class_chargement_cercle.eps \
    documentation/latex/class_chargement_cercle.tex \
    documentation/latex/class_chargement_facade.eps \
    documentation/latex/class_chargement_facade.tex \
    documentation/latex/class_chargement_groupe.eps \
    documentation/latex/class_chargement_groupe.tex \
    documentation/latex/class_chargement_polygone.eps \
    documentation/latex/class_chargement_polygone.tex \
    documentation/latex/class_chargement_segment.eps \
    documentation/latex/class_chargement_segment.tex \
    documentation/latex/class_chargement_triangle.eps \
    documentation/latex/class_chargement_triangle.tex \
    documentation/latex/class_cpp_test.tex \
    documentation/latex/class_cpp_test_facade.tex \
    documentation/latex/class_dessinable.eps \
    documentation/latex/class_dessin_manager.eps \
    documentation/latex/class_erreur.tex \
    documentation/latex/class_exception_couleur_inexistante.eps \
    documentation/latex/class_exception_couleur_inexistante.tex \
    documentation/latex/class_exception_traitement_impossible.eps \
    documentation/latex/class_exception_traitement_impossible.tex \
    documentation/latex/class_expert.eps \
    documentation/latex/class_expert.tex \
    documentation/latex/class_expert_chargement.eps \
    documentation/latex/class_expert_chargement.tex \
    documentation/latex/class_expert_c_o_r.eps \
    documentation/latex/class_expert_c_o_r.tex \
    documentation/latex/class_facade.tex \
    documentation/latex/class_forme_composee.eps \
    documentation/latex/class_forme_composee.tex \
    documentation/latex/class_forme_geom.eps \
    documentation/latex/class_forme_geom.tex \
    documentation/latex/class_groupe.eps \
    documentation/latex/class_main_window.eps \
    documentation/latex/class_main_window.tex \
    documentation/latex/class_matrice_carree2.tex \
    documentation/latex/class_objet_geom.eps \
    documentation/latex/class_objet_geom.tex \
    documentation/latex/class_point.eps \
    documentation/latex/class_point.tex \
    documentation/latex/class_polygone.eps \
    documentation/latex/class_segment.eps \
    documentation/latex/class_segment.tex \
    documentation/latex/class_triangle.eps \
    documentation/latex/class_triangle.tex \
    documentation/latex/class_vecteur.tex \
    documentation/latex/dir_3fe1b540d32f99d66521f4d105e848f4.tex \
    documentation/latex/dir_6e88fadedb5d110c56555910975b1e36.tex \
    documentation/latex/dir_59425e443f801f1f2fd8bbe4959a3ccf.tex \
    documentation/latex/dir_68267d1309a1af8e8297ef4c3efbcdba.tex \
    documentation/latex/dir_fceced95d8215eeebebd9df6aa39e1a5.tex \
    documentation/latex/doxygen.sty \
    documentation/latex/hierarchy.tex \
    documentation/latex/Makefile \
    documentation/latex/refman.tex

RESOURCES += \
    images.qrc
